### ISSUE TITLE
Vendored cgo fails if a headers etc. needed

### ISSUE THREAD

**Issue by lstoll** [mikedanese/gazel#22]
If a vendored item depends on headers in the repo, it fails with the generated rule like:

```
ERROR: /home/lincoln.stoll/src/github.com/heroku/vendor/BUILD:2057:1: C++ compilation of rule '//vendor:github.com/erikdubbelboer/gspt_cgo.cgo.dir/gen/_cgo_lib' failed: linux-sandbox failed: error executing command /media/data/.cache/bazel/_bazel_lincoln.stoll/634c69ae0c5fc3015b4adea04323e7ab/execroot/_bin/linux-sandbox ... (remaining 43 argument(s) skipped).
/media/data/.cache/bazel/_bazel_lincoln.stoll/634c69ae0c5fc3015b4adea04323e7ab/bazel-sandbox/6cf18494-01f4-49d6-870b-bb664034f3b5-0/execroot/bazel-out/local-fastbuild/genfiles/vendor/github.com/erikdubbelboer/gspt_cgo.cgo.dir/src/vendor/github.com/erikdubbelboer/gspt/gspt.go:5:26: fatal error: setproctitle.h: No such file or directory
```

This seems to be because the gcc command runs in the sandbox root, but the header is in the `vendor/xxx` path so it isn't found. `cgo_library` seems like it would/could fix this by passing in that path as an include path (https://github.com/bazelbuild/rules_go/blob/master/go/def.bzl#L937-L938), but this isn't possible with `cgo_genrule`

I'm happy to have a go at a fix, but I was wondering what the reason was for switching to `cgo_genrule` in the first place?

**Comment by mikedanese** [comment]
Yup, I think @spxtr has run into this before. We fixed it like this:

https://github.com/kubernetes/test-infra/blob/master/vendor/BUILD#L292-L295

Is this the same issue?

I think this is less of a problem with the go build rules and more of a problem with us forcing a single vendor BUILD file. The go rules add the directory that the rule exists in as an include path but that breaks down when cgo source files are deep in subdirectories of a bazel package. I'm open to fixing this in gazel (i.e. automatically adding the include to cgo_genrules in vendor/) but maybe this is solvable by making rules_go a bit smarter.

@pmbethe09 might be interested.

**Comment by mikedanese** [comment]
IMO the bulk of the complexity of the go build rules is getting them to play nicely with c++ code unfortunately and there are still some unsolved problems. Both cgo_genrule and cgo_library use _setup_cgo_library (function you linked). I see 3 potential options here:

1. Modify _setup_cgo_library to add an include for the some subpath if source files for the rule are in subdirectories. e.g. the longest common subpath of sources might work well.
2. Forward an [includes](https://bazel.build/versions/master/docs/be/c-cpp.html#cc_library.includes) attribute from cgo_genrule and cgo_library to the cc_library.
3. Use the copts workaround and maybe add it to cgo_genrules in vendor by default with gazel.

cgo_library breaks in other ways so I'd like to avoid it. See https://github.com/bazelbuild/rules_go/issues/201

**Comment by lstoll** [comment]
Yep, it's the same issue. I somehow passed over `cgo_genrule` accepting copts as well, so I just added that and removed the automanaged tag

I think going forward option 1 is likely the best plan. If the rules are meant to maintain interop with the normal go tooling I can't see a case where that wouldn't be desired. I think solving it in rules_go is probably more valid than here, so I'll have a go at that.

Thanks for the clarification!
