### ISSUE TITLE
--root causing trouble

### ISSUE THREAD

**Issue by spxtr** [mikedanese/gazel#23]
```bash
$ go get -u gopkg.in/mikedanese/gazel.v10/gazel
$ gazel
$ gazel --root "."
$ gazel --root "${PWD}"
wrote "/home/me/go/src/foo/bar/BUILD"
wrote "foo/bar/BUILD"
```

**Comment by mikedanese** [comment]
I think we decided this is specifically when using "AddSourcesRules" which is a brand new feature.

**Comment by ixdy** [comment]
there are a few bugs here. the `AddSourcesRules` has one bug, which is an easy fix. but v8 is also broken; if I run gazel from a subdir of a repo (e.g. k8s.io/test-infra/prow) it doesn't work, either:
```console
~/.../k8s.io/test-infra/prow $ $GOPATH/bin/gazel --root=../ --print-diff --dry-run
F0104 14:36:20.488817   32717 gazel.go:51] err walking vendor: lstat vendor/: no such file or directory
...
```
