### ISSUE TITLE
removes "go_prefix" from root BUILD file

### ISSUE THREAD

**Issue by emcfarlane** [mikedanese/gazel#29]
Running gazel removes "go_prefix" from the root BUILD file.

```
-load("@io_bazel_rules_go//go:def.bzl", "go_prefix")
+load("@io_bazel_rules_go//go:def.bzl")
```

**Comment by ixdy** [comment]
#28 
this is why we need tests...

**Comment by spxtr** [comment]
> this is why we need tests...

Even something super simple in travis will suffice, such as `gazel && bazel build //...`.
