### ISSUE TITLE
Please add --version or --help or similar

### ISSUE THREAD

**Issue by MarkusTeufelberger** [mikedanese/gazel#35]
Currently gazel does not print its version number and help text is sent to stdout.

I wanted to know which version of gazel I am currently using on my CI server to generate my go BUILD files and  wasn't able to do so easily. Additionally, it would be nice to have a command that exits with a 0 but doesn't write anywhere except stdout (like --version or --help) for quick smoke tests.

**Comment by ixdy** [comment]
@MarkusTeufelberger what are you attempting to do in smoke tests?

**Comment by MarkusTeufelberger** [comment]
Run something like "go get github.com/mikedanese/gazel/gazel" and then afterwards run "gazel --version" to see if the binary really is present in $PATH or if I made a mistake when setting up e.g. environment vars in a container.

Right now I don't see any command that I could quickly and cheaply run that doesn't require any config files or repositories to create BUILD files for.

**Comment by spxtr** [comment]
`$ which gazel` :)

I would like `gazel --version`.

**Comment by ixdy** [comment]
Not sure how we'd get `--version` with a `go get`'d binary.

We could probably stamp releases with Bazel and upload binaries to GitHub, though.

**Comment by spxtr** [comment]
Yeah, I'm not sure how that'd work without doing a release process that's more complicated than `git tag`. Might not be worth it. `which gazel` answers "do I have gazel somewhere in my path".

**Comment by MarkusTeufelberger** [comment]
It does answer "there is a binary named gazel in $PATH and this is its location" - it doesn't answer the question "it will be possible to execute this binary on this machine". I can copy a 64 bit binary in the $PATH of a 32 bit machine and "which foo" will happily return.

**Comment by abijr** [comment]
You don't need to start versioning gazel, you could just use the commit hash or build date. 
And the issue mentions "--help or --version" just a help message might be enough for the use case,

**Comment by spxtr** [comment]
Commit hash and build date aren't easy to make work with `go get`, but there might be a good pattern I'm just not aware of.

**Comment by MarkusTeufelberger** [comment]
Project is deprecated, closing.
