### ISSUE TITLE
remove hardcoding of kubernetes specific paths

### ISSUE THREAD

**Issue by mikedanese** [mikedanese/gazel#5]
Right now gazel is coded to the kubernetes repository. It should be possible to run gazel on other go repos without forking. A json or yaml config file in the repo root might work.

cc @justinsb since you may have already done this. @pjjw since I see you've forked gazel because this feature didn't exist.

**Comment by mikedanese** [comment]
https://github.com/mikedanese/gazel/pull/7 adds support for json config

**Comment by pjjw** [comment]
oh, thank you! :)
